spring:
 datasource:
  url: jdbc:mysql://localhost:3306/ecsite
  username: root
  password: yamaoka8610
  driverClassName: com.mysql.cj.jdbc.Driver
#mybatis:
# configuration-properties:
#  dbschema: schemaname
server:
 servlet:
  context-path: /ec-site
